# Generated by Django 5.2.8 on 2025-12-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_add_current_collection_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_collection_id',
            field=models.CharField(editable=False, max_length=36),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_workspace_id',
            field=models.CharField(editable=False, max_length=36),
        ),
    ]
