# Generated by Django 5.2.8 on 2026-01-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_unneeded_null_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_time_nagged',
        ),
    ]
