# Generated by Django 5.2.10 on 2026-01-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_nagging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_pdfs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pdfs_total_size',
        ),
    ]
