# Generated by Django 5.2.11 on 2026-03-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_pdf_stats_from_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='layout',
            field=models.CharField(
                choices=[('Compact', 'Compact'), ('List', 'List'), ('Grid', 'Grid'), ('Minimal', 'Minimal')],
                default='Compact',
                max_length=7,
            ),
        ),
    ]
