# Generated by Django 5.2.12 on 2026-03-15 17:58

from django.db import migrations


def creme_to_dark(apps, schema_editor):  # pragma: no cover
    """Switch creme theme to dark theme as creme theme is removed."""

    Profile = apps.get_model('users', 'Profile')
    Profile.objects.filter(dark_mode='Creme').update(dark_mode='Dark')


def reverse_func(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_add_minimal_layout'),
    ]

    operations = [migrations.RunPython(creme_to_dark, reverse_func)]
