# Generated by Django 5.2.12 on 2026-03-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_creme_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(
                choices=[('Auto', 'Auto'), ('English', 'English')], default='English', max_length=30
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dark_mode',
            field=models.CharField(
                choices=[('System', 'System'), ('Light', 'Light'), ('Dark', 'Dark')], default='Dark', max_length=6
            ),
        ),
    ]
