# Generated by Django 5.2.14 on 2026-06-22 01:48

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_add_language_adjust_theme_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_time_nagged',
            field=models.DateTimeField(default=users.models.get_last_time_nagged_initial),
        ),
    ]
