# Generated by Django 5.2.15 on 2026-07-25 22:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


def fill_pdf_reading_info(apps, schema_editor):
    """Fill the pdf reading info for all pdfs"""

    Pdf = apps.get_model('pdf', 'Pdf')
    PdfReadingInformation = apps.get_model('users', 'PdfReadingInformation')
    db_alias = schema_editor.connection.alias

    for pdf in Pdf.objects.all():
        workspace = pdf.collection.workspace
        # currently each workspace only has a single user
        workspace_user = workspace.workspaceuser_set.first()

        # just to be sure a check if there is actually a user
        if workspace_user:
            profile = workspace_user.user.profile

            PdfReadingInformation.objects.using(db_alias).create(
                profile=profile,
                pdf=pdf,
                current_page=pdf.current_page,
                last_viewed_date=pdf.last_viewed_date,
                views=pdf.views,
            )


def reverse_func(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0030_increase_pdf_name_length'),
        ('users', '0031_add_nagging'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfReadingInformation',
            fields=[
                ('last_viewed_date', models.DateTimeField(editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_page', models.IntegerField()),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.pdf')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.RunPython(fill_pdf_reading_info, reverse_func),
    ]
