# Generated by Django 5.2.16 on 2026-08-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_pdf_reading_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='custom_theme_color',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='custom_theme_color_secondary',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='theme_color',
        ),
    ]
