# Generated by Django 6.1 on 2026-08-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_theme_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='minutes_spent_reading',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
