# Generated by Django 5.2.8 on 2025-11-23 19:49

from shutil import move

from core.settings import MEDIA_ROOT
from django.db import migrations


def adjust_file_paths(apps, schema_editor):  # pragma: no cover
    """
    Adjust the file paths of all PDFs and shared PDFs so that the include the workspace id
    and collection name. As only the default collection exists, result will look like
    1/default/...
    """

    pdf_model = apps.get_model('pdf', 'Pdf')
    shared_pdf_model = apps.get_model('pdf', 'SharedPdf')
    user_model = apps.get_model('auth', 'User')

    for pdf_object in pdf_model.objects.all():
        try:
            # adjust pdf file
            user_id, rest_of_file_name = pdf_object.file.name.split('/', maxsplit=1)
            pdf_object.file.name = '/'.join([user_id, 'default', rest_of_file_name])

            # adjust pdf preview file
            user_id, rest_of_file_name = pdf_object.preview.name.split('/', maxsplit=1)
            pdf_object.preview.name = '/'.join([user_id, 'default', rest_of_file_name])

            # adjust pdf thumbnail file
            user_id, rest_of_file_name = pdf_object.thumbnail.name.split('/', maxsplit=1)
            pdf_object.thumbnail.name = '/'.join([user_id, 'default', rest_of_file_name])
            pdf_object.save()
        except ValueError:  # pragma: no cover
            pass

    for shared_pdf_object in shared_pdf_model.objects.all():
        try:
            user_id, rest_of_file_name = shared_pdf_object.file.name.split('/', maxsplit=1)
            shared_pdf_object.file.name = '/'.join([user_id, 'default', rest_of_file_name])
            shared_pdf_object.save()
        except ValueError:  # pragma: no cover
            pass

    for user_object in user_model.objects.all():
        try:
            old_path = MEDIA_ROOT / str(user_object.id)
            tmp_path = MEDIA_ROOT / 'tmp' / str(user_object.id)
            new_path = MEDIA_ROOT / str(user_object.id) / 'default'

            # move all files to tmp dir first because moving into a subdir of itself will not work
            move(old_path, tmp_path)
            move(tmp_path, new_path)
        except FileNotFoundError:  # pragma: no cover
            pass


def reverse_func(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0021_adjust_workspace_role_names'),
    ]

    operations = [
        migrations.RunPython(adjust_file_paths, reverse_func),
    ]
