# Generated by Django 5.2.8 on 2025-11-23 19:49

from django.db import migrations


def adjust_file_paths(apps, schema_editor):  # pragma: no cover
    pdf_model = apps.get_model("pdf", "Pdf")

    for pdf_object in pdf_model.objects.all():
        pass


def reverse_func(apps, schema_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0021_adjust_workspace_role_names'),
    ]

    operations = [
        migrations.RunPython(adjust_file_paths, reverse_func),
    ]
