# Generated by Django 5.2.8 on 2025-11-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0022_adjust_pdf_paths_to_ws_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='owner',
        ),
    ]
