# Generated by Django 5.2.8 on 2025-12-03 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0023_remove_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.collection'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.workspace'),
        ),
    ]
