# Generated by Django 5.2.12 on 2026-03-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0024_remove_unneeded_null_true'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpdf',
            name='sessions',
            field=models.ManyToManyField(to='sessions.session'),
        ),
    ]
