# Generated by Django 5.2.14 on 2026-06-12 00:32

import uuid

import django.db.models.deletion
from django.db import migrations, models
from pdf.models.shared_models import get_collection_qr_code_path


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0025_add_session_to_shared_pdf'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='', help_text='Optional')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('max_views', models.IntegerField(blank=True, help_text='Optional', null=True)),
                ('password', models.CharField(blank=True, help_text='Optional', max_length=128, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('deletion_date', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to=get_collection_qr_code_path)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.collection')),
                ('sessions', models.ManyToManyField(to='sessions.session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
