# Generated by Django 5.2.14 on 2026-06-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0026_add_shared_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedcollection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sharedcollection',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='sharedpdf',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sharedpdf',
            name='expiration_date',
        ),
    ]
