# Generated by Django 5.2.14 on 2026-06-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0027_remove_expiration_and_description_from_shared_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedcollection',
            name='max_views',
        ),
        migrations.RemoveField(
            model_name='sharedcollection',
            name='views',
        ),
    ]
