# Generated by Django 5.2.14 on 2026-06-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0028_remove_unneeded_fields_from_shared_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
