# Generated by Django 5.2.14 on 2026-06-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0029_add_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
