name: PdfDing Publish

on:
  pull_request:
    paths: [ 'pdfding/**/*.py', 'pdfding/**/*.html', 'pyproject.toml', 'package.json' , 'Dockerfile' ]
  release:
    types:
      - released

jobs:
  release:
    name: Release
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mrmn
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: mrmn/pdfding:${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64
  dry_run:
    name: Dry run
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          outputs: type=cacheonly
